apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: fluid-system
type: Opaque
stringData:
  name: "my-jfs"                # JuiceFS 文件系统名称
  metaurl: "redis://clustercfg.dev1.gbs5t9.usw2.cache.amazonaws.com:6379/1"      # 例如 "redis://host:port/1"
  storage: "s3"                 # 存储类型
  bucket: "https://ab-23-data.us-west-2.s3.amazonaws.com"           # 例如 "https://mybucket.s3.amazonaws.com"
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}