apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: jfs-dataset
  namespace: fluid-system
spec:
  mounts:
    - mountPoint: "juicefs:///"  # JuiceFS 挂载点
      name: juicefs-mount
      options:
        bucket: "https://training-data-bkt.us-west-2.s3.amazonaws.com"      # 可选，如果与 Secret 中的不同
      encryptOptions:
        - name: metaurl
          valueFrom:
            secretKeyRef:
              name: juicefs-secret
              key: metaurl
        - name: access-key
          valueFrom:
            secretKeyRef:
              name: juicefs-secret
              key: access-key
        - name: secret-key
          valueFrom:
            secretKeyRef:
              name: juicefs-secret
              key: secret-key
