apiVersion: v1
kind: Pod
metadata:
  name: data-reader-pod
spec:
  containers:
    - name: data-reader
      image: busybox
      command: ["/bin/sh"]
      args:
        - "-c"
        - "while true; do ls -l /data; cat /data/*; sleep 30; done"  # Lists and reads files every 30 seconds
      volumeMounts:
        - name: s3-data
          mountPath: /data    # This matches the S3 data mount point
  volumes:
    - name: s3-data
      persistentVolumeClaim:
        claimName: s3-dataset  # This should match your Dataset name